name: Update entries

on: workflow_dispatch

jobs:
  update-entries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28
      - name: build
        run: nix build .
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "result"

  deploy:
    runs-on: ubuntu-latest
    needs: update-entries
    permissions:
      pages: write
      id-token: write

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
