name: Update entries

on: workflow_dispatch

jobs:
  update-entries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@6004951b182f8860210c8d6f0d808ec5b1a33d28
      - name: build
        run: nix build .
      - uses: actions/upload-pages-artifact
        with:
          path: "result"

  deploy:
    runs-on: ubuntu-latest
    needs: update-entries
    steps:
      - uses: actions/deploy-pages@v4


